---
- name: Install metricbeat and transfer configuration file to VMs
  hosts: webservers
  become: true
  tasks:

  - name: Download deb file for metricbeats
    command:
      cmd: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeatst from downloaded file
    command:
      cmd: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy metricbeat config file to VM
    copy:
      src: /etc/ansible/roles/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable metricbeat system
    command:
      cmd: metricbeat modules enable system

  - name: Setup metricbeat
    command:
      cmd: metricbeat setup

  - name: Start metricbeat service
    command:
      cmd: service metricbeat start

  - name: Enable metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
